version: '3.8'

services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: forms-app-frontend
    ports:
      - "6001:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:6002
    networks:
      - app-network


  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: forms-app-backend
    ports:
      - "6002:6002"
    environment:
      - NODE_ENV=production
      - PORT=6002
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=KnxedLtEQcrY6JvH
      - DB_NAME=forms_app
      - JWT_SECRET=g3&8{!x`d]rQs_FZV:kyGMHNYRz<p5~>
    depends_on:
      - mysql
    networks:
      - app-network


  mysql:
    image: mysql:8.0
    container_name: forms-app-sql
    environment:
      MYSQL_ROOT_PASSWORD: KnxedLtEQcrY6JvH
      MYSQL_DATABASE: forms_app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
    name: app-network
    external: true